# Site settings
title: ExploreApollo.org
email: austin@austinpray.com
description: > # this means to ignore newlines until "baseurl:"
  ExploreApollo.org uses signal, speech and language processing algorithms to
  extract new information, merge information sources, and provide a new
  perspective on the NASA Apollo missions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://exploreapollo.org" # the base hostname & protocol for your site
github_username:  UTD-CRSS

# Build settings
markdown: kramdown
